language: ruby
rvm:
  - 1.9.3
before_script: 
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare --trace
bundler_args: --without production development
branches:
  only:
    - dev
    - master
